services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=quiz
      - POSTGRES_PASSWORD=quiz
      - POSTGRES_DB=quiz_db
    volumes:
      - "./conf.d:/etc/postgres/conf.d:ro"
